// Generated by CIRCT firtool-1.62.0
module adder(
  input         clock,
                reset,
  input  [31:0] io_in_a,
                io_in_b,
  output [32:0] io_out_s
);

  assign io_out_s = {1'h0, io_in_a + io_in_b};
endmodule

